<a href="https://colab.research.google.com/github/jyotinayak321/IBM-training_-learning-/blob/main/one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv('/content/cars (1).csv')

In [22]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [25]:
df['owner'].value_counts() #how many time unique value come in the colm

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# ***OneHotEncoding using Pandas***

In [27]:
#categorical text convert into numerical colums
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# ***K-1 OneHotEncoding***

# **What is the Dummy Variable Trap?**

When all dummy variables are kept, one dummy column can be predicted from the others.

For example:

fuel_CNG + fuel_Diesel + fuel_Petrol = 1

If you know any two values, you can always determine the third. This creates perfect multicollinearity, which is called the Dummy Variable Trap.

This can cause problems for models such as Linear Regression and Logistic Regression.

In [29]:
#drop_first=True removes the first category from each categorical column after performing One-Hot Encoding
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

K-1 Encoding is a variation of One-Hot Encoding where, instead of creating K binary columns for K categories, we create only K-1 columns by dropping one category. The dropped category acts as the reference category. This helps avoid the Dummy Variable Trap (multicollinearity), especially in linear models like Linear Regression, while preserving all the information.

# **OneHotEncoding using Sklearn**

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],
                                                 df.iloc[:,-1],
                                                 test_size=0.2,
                                                 random_state=2)

train_test_split()

Ye function dataset ko Training Data aur Testing Data me divide karta hai.

*   Training Data → Model ko train karne ke liye.
*   Testing Data → Model ki performance check karne ke liye.


test_size=0.2

Matlab:

20% data Testing ke liye
80% data Training ke liye

random_state=2

Ye random splitting ko fixed karta hai.

In [32]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [38]:


ohe = OneHotEncoder(
    drop='first',
    sparse_output=False,
    dtype=np.int32
)

In [39]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [40]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

During machine learning:

Training Data → Use fit_transform()
Learns all the unique categories.
Converts them into numerical columns.

Test Data → Use only transform()

Does not learn anything new.
Uses the same categories learned from the training data.

In [41]:
X_train_new.shape

(6502, 7)

np.hstack() means Horizontal Stack.

It joins two arrays column-wise (side by side)

In [42]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

***OneHotEncoding with Top Categories***

In [44]:
counts = df['brand'].value_counts()

In [48]:
df['brand'].nunique()  #nunique() returns the number of unique (distinct) values in a column
threshold = 100

In [49]:
repl = counts[counts <= threshold].index

In [54]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6921,False,False,True,False,False,False,False,False,False,False,False,False,False
3956,False,False,False,False,False,False,True,False,False,False,False,False,False
4211,False,False,False,False,False,False,True,False,False,False,False,False,False
6245,False,False,False,False,False,False,True,False,False,False,False,False,False
834,False,False,True,False,False,False,False,False,False,False,False,False,False

Load Dataset

↓

Identify Categorical Columns

↓

Check Categories (value_counts)

↓

One-Hot Encoding (Pandas)

↓

Use drop_first=True (K-1 Encoding)

↓

Split into Train & Test

↓

Create OneHotEncoder

↓
fit_transform() on Training Data
↓

transform() on Test Data

↓

Combine Encoded Features (np.hstack)

↓

Check High Cardinality (nunique, value_counts)

↓

Replace Rare Categories with "uncommon"

↓

One-Hot Encode Again

↓

Final Feature Matrix Ready for Machine Learning