<a href="https://colab.research.google.com/github/jyotinayak321/IBM-training_-learning-/blob/main/Panda_DATAFRAME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
d = {"product":["a","B","C","D","E"],
     "Amount": [1,2,3,4,np.nan]}              #NAN is data missing value
d

{'product': ['a', 'B', 'C', 'D', 'E'], 'Amount': [1, 2, 3, 4, nan]}

In [ ]:
# create a DataFrame
df = pd.DataFrame(d)

In [ ]:
df["New_Col"] = np.nan
df

  product  Amount  New_Col
0       a     1.0      NaN
1       B     2.0      NaN
2       C     3.0      NaN
3       D     4.0      NaN
4       E     NaN      NaN

In [ ]:
df.columns

Index(['product', 'Amount', 'New_Col'], dtype='object')

In [ ]:
df.drop(columns="New_Col", inplace=True)
df.columns

Index(['product', 'Amount'], dtype='object')

In [ ]:
df.rename(columns= {"Product":"Item"},inplace=True)

In [ ]:
df.columns

Index(['product', 'Amount'], dtype='object')

In [ ]:
df.rename(columns={"Amount": "Price"}, inplace=True)

In [ ]:
df.columns

Index(['product', 'Price'], dtype='object')

In [ ]:
df["Price"].fillna(200, inplace=True)

/tmp/ipykernel_1337/667004765.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(200, inplace=True)
/tmp/ipykernel_1337/667004765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"].fillna(200, inplace=True)

In [ ]:
df = df[["Price", "product"]]

In [ ]:
df["Price"].iloc[3]=0
df

/tmp/ipykernel_1337/1119535683.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Price"].iloc[3]=0
/tmp/ipykernel_1337/1119535683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"].iloc[3]=0

   Price product
0    1.0       a
1    2.0       B
2    3.0       C
3    0.0       D
4  200.0       E

In [ ]:
df["Location"] = ["Delhi", "Mumbai", "Chennai", "Kolkata", "Bangalore"]

In [ ]:
len(df)

5

In [ ]:
df.shape # it will shows the shape of the df

(5, 3)

In [ ]:
df  # it will show your dataframe work

   Price product   Location
0    1.0       a      Delhi
1    2.0       B     Mumbai
2    3.0       C    Chennai
3    0.0       D    Kolkata
4  200.0       E  Bangalore

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.head()

   Price product   Location
0    1.0       a      Delhi
1    2.0       B     Mumbai
2    3.0       C    Chennai
3    0.0       D    Kolkata
4  200.0       E  Bangalore

In [ ]:
df.tail()

   Price product   Location
0    1.0       a      Delhi
1    2.0       B     Mumbai
2    3.0       C    Chennai
3    0.0       D    Kolkata
4  200.0       E  Bangalore

In [ ]:
pd.set_option('display.max_columns',None)

In [ ]:
df = pd.read_excel("SuperStore.xls")   #loading dataset

In [ ]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [ ]:
df.info()  # symmery of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [ ]:
df.head(2)  # we use head for specific top 5 but as we menton the top 2

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870

In [ ]:
df.tail(2)   # we use  the tail for the bottom top 5 but and as we want speciafic value

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10192,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [ ]:
df.sample(15)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5178,5179,US-2025-156685,2025-07-08,2025-07-10,Second Class,SC-20230,Scot Coram,Corporate,United States,Arlington,Texas,76017,Central,TEC-PH-10004345,Technology,Phones,Cisco SPA 502G IP Phone,863.640,9,0.2,107.9550
825,826,US-2023-169019,2023-07-26,2023-07-30,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,Texas,78207,Central,TEC-AC-10002076,Technology,Accessories,Microsoft Natural Keyboard Elite,431.136,9,0.2,-26.9460
6381,6382,US-2025-163881,2025-11-24,2025-11-30,Standard Class,SP-20860,Sung Pak,Corporate,United States,Los Angeles,California,90036,West,TEC-AC-10000420,Technology,Accessories,Logitech G500s Laser Gaming Mouse with Adjusta...,559.920,8,0.0,190.3728
5446,5447,US-2025-158001,2025-08-23,2025-08-27,Standard Class,JP-15460,Jennifer Patt,Corporate,United States,New York City,New York,10035,East,OFF-AR-10001954,Office Supplies,Art,Newell 331,29.340,6,0.0,7.9218
1267,1268,US-2023-108189,2023-10-02,2023-10-05,First Class,ES-14080,Erin Smith,Corporate,United States,Tempe,Arizona,85281,West,OFF-EN-10004846,Office Supplies,Envelopes,Letter or Legal Size Expandable Poly String Ti...,12.768,6,0.2,4.6284
10074,10075,US-2026-115931,2026-12-22,2026-12-26,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Carlsbad,New Mexico,88220,West,OFF-AR-10000369,Office Supplies,Art,Design Ebony Sketching Pencil,4.170,3,0.0,1.0842
2619,2620,US-2024-100818,2024-05-31,2024-06-05,Second Class,JM-15265,Janet Molinari,Corporate,United States,Chicago,Illinois,60653,Central,OFF-BI-10004364,Office Supplies,Binders,Storex Dura Pro Binders,3.564,3,0.8,-6.2370
322,323,US-2023-102988,2023-04-05,2023-04-09,Second Class,GM-14695,Greg Maxwell,Corporate,United States,Alexandria,Virginia,22304,South,TEC-PH-10001615,Technology,Phones,AT&T CL82213,28.990,1,0.0,8.4071
2382,2383,US-2024-133837,2024-04-13,2024-04-18,Standard Class,TH-21100,Thea Hendricks,Consumer,United States,Glendale,Arizona,85301,West,OFF-ST-10000344,Office Supplies,Storage,"Neat Ideas Personal Hanging Folder Files, Black",10.744,1,0.2,0.8058
5002,5003,US-2025-147375,2025-06-12,2025-06-14,Second Class,PO-19180,Philisse Overcash,Home Office,United States,Chicago,Illinois,60623,Central,OFF-PA-10001970,Office Supplies,Paper,Xerox 1908,313.488,7,0.2,113.6394
9798,9799,US-2026-118017,2026-12-03,2026-12-06,Second Class,LC-16870,Lena Cacioppo,Consumer,United States,Thornton,Colorado,80229,West,OFF-SU-10004782,Office Supplies,Supplies,"Elite 5"" Scissors",47.320,7,0.2,5.9150
5825,5826,US-2025-125402,2025-09-25,2025-10-01,Standard Class,DL-12865,Dan Lawera,Consumer,United States,Long Beach,California,90805,West,FUR-CH-10000665,Furniture,Chairs,"Global Airflow Leather Mesh Back Chair, Black",483.136,4,0.2,60.3920
6258,6259,US-2025-121370,2025-11-14,2025-11-19,Second Class,EB-14110,Eugene Barchas,Consumer,United States,Philadelphia,Pennsylvania,19134,East,FUR-CH-10000785,Furniture,Chairs,Global Ergonomic Managers Chair,380.058,3,0.3,-21.7176
1004,1005,US-2023-106971,2023-09-02,2023-09-08,Standard Class,BM-11785,Bryan Mills,Consumer,United States,Buffalo Grove,Illinois,60089,Central,TEC-AC-10000844,Technology,Accessories,Logitech Gaming G510s - Keyboard,475.944,7,0.2,95.1888
1065,1066,US-2023-126403,2023-09-09,2023-09-12,Second Class,RR-19525,Rick Reed,Corporate,United States,Lowell,Massachusetts,1852,East,FUR-CH-10003761,Furniture,Chairs,Global Italian Leather Office Chair,785.880,6,0.0,212.1876

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [ ]:
df["Ship Mode"].unique()      #find all unique (distinct) values in a column

array(['Standard Class', 'First Class', 'Second Class', 'Same Day'],
      dtype=object)

In [ ]:
df["Ship Mode"].value_counts()   #counts how many times each unique value appears

Ship Mode
Standard Class    6120
Second Class      1979
First Class       1548
Same Day           547
Name: count, dtype: int64

In [ ]:
df.sample(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
352,353,US-2023-102715,2023-04-11,2023-04-13,Second Class,JK-15370,Jay Kimmel,Consumer,United States,Miami,Florida,33180,South,TEC-AC-10001874,Technology,Accessories,Logitech Wireless Anywhere Mouse MX for PC and...,335.944,7,0.2,41.9930
5725,5726,US-2025-162159,2025-09-16,2025-09-18,First Class,CR-12625,Corey Roper,Home Office,United States,Columbus,Georgia,31907,South,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray",121.780,2,0.0,30.4450
8144,8145,US-2026-105046,2026-07-17,2026-07-23,Standard Class,BE-11335,Bill Eplett,Home Office,United States,Rome,New York,13440,East,FUR-FU-10004848,Furniture,Furnishings,DAX Solid Wood Frames,39.080,4,0.0,14.4596

In [ ]:
df["Customer ID"]

0        DP-13000
1        PO-19195
2        PO-19195
3        PO-19195
4        MB-18085
           ...
10189    PO-18865
10190    EB-13975
10191    JM-15580
10192    PO-18865
10193    HO-15230
Name: Customer ID, Length: 10194, dtype: object

In [ ]:
df["Customer ID"].unique()

array(['DP-13000', 'PO-19195', 'MB-18085', 'ME-17320', 'JO-15145',
       'LS-17230', 'VS-21820', 'MS-17830', 'AJ-10780', 'SV-20365',
       'BD-11605', 'ND-18370', 'MM-17920', 'CS-12250', 'BS-11590',
       'EH-13990', 'DL-13315', 'DW-13195', 'TS-21340', 'HL-15040',
       'XP-21865', 'MV-17485', 'MM-18280', 'TB-21400', 'JW-15220',
       'SG-20605', 'IM-15055', 'CA-11965', 'SD-20485', 'EJ-13720',
       'JC-15340', 'MV-18190', 'LC-17050', 'BD-11500', 'EB-13930',
       'CD-12790', 'MH-17440', 'DB-13270', 'ND-18460', 'CK-12760',
       'NM-18445', 'GA-14725', 'NF-18385', 'SC-20095', 'ML-17395',
       'ST-20530', 'BF-11020', 'MN-17935', 'TB-21595', 'AB-10015',
       'LC-16930', 'SR-20740', 'TM-21010', 'SA-20830', 'MG-17875',
       'JH-15430', 'JS-16030', 'VF-21715', 'SC-20380', 'DB-13060',
       'GW-14605', 'HR-14770', 'KN-16705', 'NH-18610', 'JS-15595',
       'EJ-14155', 'SC-20020', 'AJ-10945', 'AP-10720', 'CL-12565',
       'AB-10150', 'CM-12715', 'NP-18685', 'KT-16480', 'SW-20275',
       'CK-12205', 'FM-14215', 'RB-19435', 'KA-16525', 'NF-18595',
       'CK-12325', 'DK-13225', 'JF-15295', 'NF-18475', 'RB-19465',
       'AS-10240', 'CP-12340', 'BN-11515', 'AZ-10750', 'QJ-19255',
       'EK-13795', 'SM-20320', 'SC-20050', 'MC-17605', 'GM-14440',
       'KH-16690', 'CB-12025', 'TS-21205', 'BF-11275', 'VM-21835',
       'CC-12685', 'BG-11740', 'PO-18865', 'MS-17710', 'CD-11920',
       'CA-12265', 'DK-12835', 'CS-12505', 'JD-15895', 'MP-18175',
       'CV-12295', 'DR-12940', 'MG-18145', 'MP-17470', 'SG-20890',
       'KM-16720', 'Dl-13600', 'NC-18340', 'TG-21640', 'AA-10315',
       'KB-16240', 'DD-13570', 'JO-15280', 'KH-16330', 'AH-10690',
       'RD-19585', 'KE-16420', 'MZ-17515', 'PK-18910', 'KB-16585',
       'GM-14695', 'RD-19900', 'RP-19855', 'TH-21550', 'JG-15805',
       'AY-10555', 'SC-20260', 'FH-14275', 'GP-14740', 'PJ-19015',
       'RS-19765', 'VM-21685', 'RA-19885', 'JS-15880', 'JM-15655',
       'PC-19000', 'SE-20110', 'JK-15370', 'MM-18055', 'GM-14455',
       'KN-16450', 'EH-13765', 'SV-20785', 'BF-11170', 'PS-18970',
       'SP-20650', 'JL-15835', 'AG-10390', 'BP-11230', 'AA-10375',
       'DB-13555', 'AH-10030', 'LB-16795', 'TS-21160', 'BT-11305',
       'DA-13450', 'LC-16885', 'AG-10300', 'MH-17290', 'MY-18295',
       'GB-14530', 'DS-13180', 'AI-10855', 'LA-16780', 'HG-14845',
       'LL-16840', 'KH-16360', 'JM-16195', 'AR-10510', 'CS-11860',
       'NC-18415', 'JS-15940', 'AA-10480', 'BS-11365', 'PM-18940',
       'EB-13870', 'PF-19120', 'GD-14590', 'SN-20710', 'HP-14815',
       'CT-11995', 'SB-20290', 'PG-18820', 'AF-10885', 'GM-14680',
       'VW-21775', 'PG-18895', 'BG-11695', 'HD-14785', 'RM-19375',
       'EH-14005', 'AG-10270', 'NP-18325', 'AJ-10795', 'PW-19030',
       'CC-12475', 'PA-19060', 'TT-21070', 'GA-14515', 'BS-11755',
       'JH-15820', 'TD-20995', 'RF-19345', 'MC-17590', 'CC-12430',
       'FG-14260', 'BT-11530', 'MW-18235', 'EH-14185', 'GT-14710',
       'RP-19390', 'JL-15235', 'BW-11065', 'HF-14995', 'Dp-13240',
       'MH-17785', 'LE-16810', 'MM-17260', 'PJ-18835', 'SS-20410',
       'LW-16825', 'JG-15160', 'EB-13840', 'MC-17425', 'JK-15625',
       'DW-13480', 'LT-17110', 'CR-12625', 'RE-19450', 'SC-20725',
       'RB-19795', 'BT-11440', 'GT-14635', 'BM-11785', 'SB-20170',
       'VT-21700', 'NR-18550', 'BP-11095', 'CS-11950', 'RD-19480',
       'BH-11710', 'FO-14305', 'CW-11905', 'CM-12445', 'HK-14890',
       'SR-20425', 'KL-16555', 'PS-18760', 'SC-20575', 'GH-14425',
       'JF-15415', 'DB-13660', 'MC-18100', 'NC-19470', 'Co-12640',
       'NW-18400', 'TB-21280', 'AA-10645', 'DV-13465', 'JE-15745',
       'DL-13330', 'BS-11665', 'LP-17080', 'NS-18640', 'GK-14620',
       'LM-17065', 'CA-12775', 'RW-19630', 'DL-12865', 'AR-10825',
       'RA-19915', 'HA-14905', 'MS-17980', 'BD-11620', 'EH-13945',
       'MS-17770', 'DM-13525', 'DP-13390', 'MC-17845', 'DC-12850',
       'BC-11125', 'EP-13915', 'MH-18025', 'EB-13705', 'DS-13030',
       'GH-14410', 'BM-11650', 'MH-17455', 'JK-15205', 'PV-18985',
       'AC-10420', 'ME-17725', 'SS-20515', 'BF-10975', 'AW-10930',
       'PB-19150', 'AH-10120', 'JL-15130', 'CA-12310', 'EM-14140',
       'KM-16375', 'CC-12145', 'SW-20245', 'RD-19720', 'ME-18010',
       'HM-14860', 'EM-14065', 'AB-10255', 'JL-15850', 'AG-10900',
       'NC-18535', 'KL-16645', 'SG-20470', 'LF-17185', 'CL-11890',
       'AS-10045', 'BB-10990', 'TS-21430', 'IL-15100', 'AS-10630',
       'NZ-18565', 'BK-11260', 'VD-21670', 'RS-19420', 'CS-12130',
       'GZ-14470', 'SS-20590', 'RF-19735', 'TB-21625', 'VG-21790',
       'MB-17305', 'LR-16915', 'MA-17560', 'DB-13405', 'JH-15985',
       'ED-13885', 'GM-14500', 'AG-10525', 'MG-17650', 'BW-11200',
       'DH-13675', 'CS-12175', 'CS-12355', 'KH-16510', 'TS-21610',
       'DJ-13510', 'LH-16900', 'JB-15400', 'DO-13645', 'CR-12730',
       'DE-13255', 'JP-15520', 'AP-10915', 'RB-19645', 'RH-19495',
       'JP-15460', 'DW-13585', 'JM-15265', 'JE-15715', 'RC-19960',
       'MW-18220', 'KB-16315', 'PP-18955', 'FM-14290', 'CC-12610',
       'ZD-21925', 'RA-19945', 'HH-15010', 'AT-10735', 'SJ-20500',
       'LT-16765', 'KD-16345', 'MR-17545', 'PR-18880', 'NP-18700',
       'VP-21760', 'SZ-20035', 'LR-17035', 'DK-13375', 'MC-17275',
       'BM-11140', 'KT-16465', 'SP-20620', 'LH-17020', 'KC-16255',
       'RR-19525', 'LC-17140', 'MS-17365', 'CC-12220', 'DL-12925',
       'SF-20065', 'AR-10345', 'LW-17125', 'LW-17215', 'TA-21385',
       'BN-11470', 'PT-19090', 'EA-14035', 'JM-15535', 'ON-18715',
       'JC-15775', 'DM-13015', 'AJ-10960', 'MF-18250', 'JA-15970',
       'AG-10765', 'JK-15640', 'FA-14230', 'MC-18130', 'DN-13690',
       'SB-20185', 'PF-19165', 'MA-17995', 'ES-14020', 'HG-14965',
       'SL-20155', 'LH-16750', 'JG-15115', 'AS-10090', 'VG-21805',
       'TT-21220', 'JP-16135', 'TH-21115', 'JD-16060', 'MT-18070',
       'BF-11005', 'KF-16285', 'NB-18580', 'CS-12400', 'TH-21100',
       'KD-16495', 'GZ-14545', 'LD-17005', 'SM-20950', 'EB-14170',
       'KW-16570', 'DM-12955', 'DB-13615', 'ES-14080', 'AR-10405',
       'BP-11290', 'RD-19930', 'DO-13435', 'DF-13135', 'JD-16015',
       'BD-11635', 'GG-14650', 'AM-10360', 'TN-21040', 'FC-14335',
       'HA-14920', 'JF-15565', 'BP-11050', 'ZC-21910', 'SP-20545',
       'TC-21295', 'HG-15025', 'JE-15610', 'AC-10660', 'LS-17245',
       'TB-21520', 'AS-10225', 'LS-17200', 'IG-15085', 'RP-19270',
       'JF-15490', 'EH-14125', 'MP-17965', 'FH-14365', 'LS-16975',
       'SF-20965', 'MG-17680', 'DB-12910', 'AH-10585', 'RD-19810',
       'TS-21370', 'BT-11395', 'NC-18625', 'AM-10705', 'AC-10450',
       'NL-18310', 'DG-13300', 'KH-16630', 'PL-18925', 'SH-20395',
       'SW-20755', 'JK-16120', 'PO-18850', 'TC-21535', 'DM-13345',
       'MS-17530', 'WB-21850', 'TH-21235', 'BG-11035', 'MD-17350',
       'TC-20980', 'BF-11215', 'TZ-21580', 'KD-16270', 'PK-19075',
       'DB-12970', 'RF-19840', 'RM-19675', 'JL-15505', 'ML-17410',
       'CM-11815', 'JF-15190', 'PB-19105', 'JD-16150', 'AB-10165',
       'AH-10075', 'RH-19510', 'RB-19330', 'YC-21895', 'JK-15730',
       'MK-17905', 'PW-19240', 'AB-10600', 'JC-16105', 'GR-14560',
       'DB-13360', 'AD-10180', 'JM-15865', 'DH-13075', 'JK-15325',
       'SC-20680', 'TC-21475', 'SP-20920', 'SS-20140', 'SM-20005',
       'PB-19210', 'NG-18355', 'NG-18430', 'AT-10435', 'HR-14830',
       'DK-12985', 'JP-11135', 'AR-10540', 'BF-11080', 'MO-17500',
       'MC-17635', 'BT-11680', 'BS-11380', 'AH-10210', 'TR-21325',
       'DP-13165', 'MD-17860', 'MC-17575', 'EM-13825', 'KN-16390',
       'MK-19560', 'CP-12085', 'JB-15925', 'RL-19615', 'NB-18655',
       'RC-19825', 'DK-13150', 'FP-14320', 'DJ-13420', 'TB-21250',
       'TB-21175', 'SH-19975', 'LH-17155', 'CY-12745', 'KC-16675',
       'RA-19285', 'SS-20875', 'CS-11845', 'SP-20860', 'SH-20635',
       'CC-12100', 'SC-20305', 'SC-20695', 'EC-14050', 'IM-15070',
       'MK-18160', 'TS-21505', 'PS-19045', 'AB-10105', 'KM-16660',
       'TW-21025', 'CC-12670', 'SF-20200', 'CK-12595', 'MG-17695',
       'TB-21190', 'MG-17890', 'RE-19405', 'DC-13285', 'BG-18435',
       'KB-16600', 'MF-17665', 'HO-15230', 'PC-18745', 'JL-15175',
       'CB-12535', 'AH-10465', 'AG-10495', 'CS-12490', 'YS-21880',
       'KS-16300', 'CR-12820', 'RW-19540', 'TS-21655', 'LO-17170',
       'SJ-20215', 'GT-14755', 'LC-16960', 'NP-18670', 'TP-21565',
       'DK-13090', 'AH-10195', 'JJ-15445', 'DK-12895', 'TG-21310',
       'EB-13750', 'JE-15475', 'CM-12385', 'CM-12655', 'JO-15550',
       'BW-11110', 'JW-16075', 'FW-14395', 'DB-13210', 'BP-11185',
       'BV-11245', 'CM-12115', 'MO-17950', 'JD-15790', 'RD-19660',
       'EB-14110', 'HJ-14875', 'AW-10840', 'TP-21130', 'OT-18730',
       'JK-16090', 'LS-16945', 'DB-13120', 'JB-16045', 'LC-16870',
       'SV-20815', 'AG-10675', 'RO-19780', 'JH-16180', 'NK-18490',
       'EN-13780', 'BD-11560', 'BD-11320', 'ML-18265', 'CG-12040',
       'BP-11155', 'BB-11545', 'EM-13810', 'MJ-17740', 'GB-14575',
       'JH-15910', 'FC-14245', 'SN-20560', 'SC-20770', 'SW-20455',
       'CH-12070', 'RH-19600', 'BD-11725', 'VP-21730', 'KM-16225',
       'FM-14380', 'VB-21745', 'TS-21085', 'RK-19300', 'BE-11455',
       'PN-18775', 'EM-14095', 'PO-19180', 'TT-21265', 'JW-15955',
       'SC-20440', 'RB-19705', 'DP-13105', 'FH-14350', 'KW-16435',
       'CA-12055', 'NM-18520', 'BO-11425', 'KD-16615', 'BM-11575',
       'AC-10615', 'MO-17800', 'AB-10060', 'CM-12190', 'JR-16210',
       'SJ-20125', 'CM-11935', 'DR-12880', 'BS-11800', 'HW-14935',
       'EM-13960', 'HM-14980', 'JJ-15760', 'GH-14485', 'SO-20335',
       'CG-12520', 'JF-15355', 'MY-17380', 'SG-20080', 'EG-13900',
       'KC-16540', 'CB-12415', 'MT-17815', 'MZ-17335', 'GH-14665',
       'KB-16405', 'PB-18805', 'TP-21415', 'RH-19555', 'MH-17620',
       'SU-20665', 'AF-10870', 'TT-21460', 'SC-20800', 'DJ-13630',
       'PM-19135', 'EM-14200', 'ER-13855', 'JR-15670', 'DL-13495',
       'BT-11485', 'BO-11350', 'EB-13975', 'JB-16000', 'BE-11335',
       'TB-21355', 'HE-14800', 'BE-11410', 'DW-13540', 'JG-15310',
       'CJ-12010', 'BD-11770', 'HZ-14950', 'SV-20935', 'JT-12540',
       'JM-15250', 'RB-19360', 'SW-20350', 'JM-15580', 'CR-12580',
       'EL-13735', 'CL-12700', 'RB-19570', 'CM-12235', 'SM-20905',
       'LW-16990', 'CV-12805', 'AS-10285', 'CC-12370', 'RW-19690',
       'LP-17095', 'SC-20230', 'RS-19870', 'DV-13045', 'HO-15234',
       'HO-15233', 'HO-15232', 'HO-15231', 'JS-15685', 'TB-21055',
       'LD-16855', 'PF-19225', 'AR-10570', 'LB-16735', 'AG-10330',
       'ML-17755', 'AO-10810', 'MH-18115', 'JS-13215', 'CM-12160',
       'SC-20845', 'AS-10135', 'RR-19315', 'NS-18505', 'CD-11980',
       'SK-19990', 'JE-16165', 'CJ-11875', 'RM-19750', 'ML-18040',
       'TM-21490', 'MG-18205', 'CC-12550', 'CS-12460', 'JC-15385',
       'TC-21145', 'PH-18790', 'JR-15700', 'CD-12280'], dtype=object)

In [ ]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2702,2703,US-2024-118955,2024-06-16,2024-06-20,Standard Class,LS-17230,Lycoris Saunders,Consumer,United States,Grand Prairie,Texas,75051,Central,OFF-EN-10001028,Office Supplies,Envelopes,Staple envelope,28.752,3,0.2,9.3444
3036,3037,US-2024-139584,2024-08-24,2024-08-28,Standard Class,EM-13810,Eleni McCrary,Corporate,United States,New York City,New York,10009,East,TEC-AC-10001266,Technology,Accessories,Memorex Micro Travel Drive 8 GB,26.000,2,0.0,11.7000
4107,4108,US-2024-158456,2024-12-24,2024-12-29,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Los Angeles,California,90032,West,OFF-BI-10001097,Office Supplies,Binders,Avery Hole Reinforcements,19.936,4,0.2,7.2268
948,949,US-2023-124737,2023-08-23,2023-08-27,Standard Class,AP-10915,Arthur Prichep,Consumer,United States,Denver,Colorado,80219,West,OFF-PA-10001837,Office Supplies,Paper,Xerox 1976,15.552,3,0.2,5.4432
5651,5652,US-2025-103709,2025-09-08,2025-09-15,Standard Class,LP-17095,Liz Preis,Consumer,United States,Visalia,California,93277,West,OFF-PA-10004610,Office Supplies,Paper,Xerox 1900,34.240,8,0.0,15.4080

In [ ]:
df["Region"]

0        Central
1        Central
2        Central
3        Central
4           East
          ...
10189       East
10190       West
10191       West
10192       East
10193       East
Name: Region, Length: 10194, dtype: object

In [ ]:
df["Region"].unique()

array(['Central', 'East', 'South', 'West'], dtype=object)

In [ ]:
df["Region"].value_counts()

Region
West       3253
East       2986
Central    2335
South      1620
Name: count, dtype: int64

In [ ]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9036,9037,US-2026-151596,2026-10-08,2026-10-11,First Class,BP-11050,Barry Pond,Corporate,United States,Cranston,Rhode Island,2920,East,OFF-ST-10001837,Office Supplies,Storage,"SAFCO Mobile Desk Side File, Wire Frame",42.760,1,0.0,11.1176
1668,1669,US-2023-157385,2023-11-23,2023-11-25,First Class,SC-20095,Sanjit Chand,Consumer,United States,Los Angeles,California,90004,West,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,603.920,5,0.2,-67.9410
982,983,US-2023-101266,2023-08-27,2023-08-30,Second Class,MM-17920,Michael Moore,Consumer,United States,Springfield,Virginia,22153,South,OFF-PA-10002986,Office Supplies,Paper,Xerox 1898,13.360,2,0.0,6.4128
1744,1745,US-2023-121629,2023-11-28,2023-12-02,Standard Class,BT-11680,Brian Thompson,Consumer,United States,Houston,Texas,77041,Central,TEC-MA-10004679,Technology,Machines,StarTech.com 10/100 VDSL2 Ethernet Extender Kit,998.850,5,0.4,-199.7700
8502,8503,US-2026-157987,2026-09-02,2026-09-06,Standard Class,AC-10615,Ann Chong,Corporate,United States,New York City,New York,10009,East,OFF-BI-10004970,Office Supplies,Binders,"ACCOHIDE 3-Ring Binder, Blue, 1""",26.432,8,0.2,8.9208

In [ ]:
df["Category"]

0        Office Supplies
1        Office Supplies
2        Office Supplies
3        Office Supplies
4        Office Supplies
              ...
10189    Office Supplies
10190    Office Supplies
10191    Office Supplies
10192         Technology
10193    Office Supplies
Name: Category, Length: 10194, dtype: object

In [ ]:
df["Category"].unique()

array(['Office Supplies', 'Furniture', 'Technology'], dtype=object)

In [ ]:
df["Category"].value_counts()

Category
Office Supplies    6128
Furniture          2201
Technology         1865
Name: count, dtype: int64

In [ ]:
df.sample(6)  #does not follow the original sequence because it is designed to return random rowsand as i speciafilly

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9250,9251,US-2026-117114,2026-10-31,2026-11-05,Standard Class,CY-12745,Craig Yedwab,Corporate,United States,Chicago,Illinois,60610,Central,OFF-EN-10001137,Office Supplies,Envelopes,"#10 Gummed Flap White Envelopes, 100/Box",9.912,3,0.2,3.2214
5328,5329,US-2025-137743,2025-07-30,2025-08-04,Standard Class,KH-16360,Katherine Hughes,Consumer,United States,Chicago,Illinois,60623,Central,OFF-LA-10003663,Office Supplies,Labels,Avery 498,9.248,4,0.2,3.1212
5655,5656,US-2025-108987,2025-09-08,2025-09-10,Second Class,AG-10675,Anna Gayman,Consumer,United States,Houston,Texas,77036,Central,TEC-AC-10000158,Technology,Accessories,Sony 64GB Class 10 Micro SDHC R40 Memory Card,57.584,2,0.2,0.7198
9724,9725,US-2026-135860,2026-12-01,2026-12-07,Standard Class,JH-15985,Joseph Holt,Consumer,United States,Saginaw,Michigan,48601,Central,OFF-BI-10003274,Office Supplies,Binders,"Avery Durable Slant Ring Binders, No Labels",15.920,4,0.0,7.4824
5381,5382,US-2025-155845,2025-08-12,2025-08-15,Second Class,CM-12235,Chris McAfee,Consumer,United States,Carrollton,Texas,75007,Central,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,1399.944,7,0.2,52.4979
9330,9331,US-2026-118213,2026-11-05,2026-11-07,First Class,AB-10060,Adam Bellavance,Home Office,United States,Greenwood,Indiana,46142,Central,OFF-PA-10002615,Office Supplies,Paper,"Ampad Gold Fibre Wirebound Steno Books, 6"" x 9...",4.410,1,0.0,2.0286

In [ ]:
df[df["Order Date"].dt.year==2023]  #This filters the DataFrame and keeps only the rows where the year is 2023.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2046,2047,US-2023-111150,2023-12-31,2024-01-04,Standard Class,RW-19630,Rob Williams,Corporate,United States,Columbia,Missouri,65203,Central,TEC-AC-10000290,Technology,Accessories,Sabrent 4-Port USB 2.0 Hub,47.530,7,0.0,16.1602
2047,2048,US-2023-143231,2023-12-31,2024-01-03,First Class,GM-14455,Gary Mitchum,Home Office,United States,Franklin,Massachusetts,2038,East,TEC-AC-10000358,Technology,Accessories,Imation Secure Drive + Hardware Encrypted USB ...,113.970,3,0.0,27.3528
2048,2049,US-2023-133592,2023-12-31,2024-01-07,Standard Class,KM-16375,Katherine Murray,Home Office,United States,Providence,Rhode Island,2908,East,TEC-AC-10002049,Technology,Accessories,Plantronics Savi W720 Multi-Device Wireless He...,1687.800,4,0.0,742.6320
2049,2050,US-2023-157644,2023-12-31,2024-01-01,First Class,AH-10030,Aaron Hawkins,Corporate,United States,New York City,New York,10035,East,TEC-AC-10003614,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,34.770,3,0.0,11.4741
2050,2051,US-2023-133949,2023-12-31,2023-12-31,Same Day,JL-15175,James Lanier,Home Office,United States,Reno,Nevada,89502,West,TEC-PH-10004908,Technology,Phones,Panasonic KX TS3282W Corded phone,475.944,7,0.2,59.4930

In [ ]:
df[df["Order Date"].dt.year==2023]["Order Date"]
#Filters the DataFrame to keep only rows where the year is 2023.
#Selects only the "Order Date" column from those filtered rows.

0      2023-01-03
1      2023-01-04
2      2023-01-04
3      2023-01-04
4      2023-01-05
          ...
2046   2023-12-31
2047   2023-12-31
2048   2023-12-31
2049   2023-12-31
2050   2023-12-31
Name: Order Date, Length: 2051, dtype: datetime64[ns]

In [ ]:
df[df["Order Date"].dt.year==2023]["Order Date"].dt.year.unique()

         #.unique() when you want the distinct value

array([2023], dtype=int32)

In [ ]:
df[df["Order Date"].dt.year==2023]["Order Date"].dt.month.value_counts()

#.value_counts() when you want both the distinct values and how many times

Order Date
11    320
12    297
9     273
10    168
3     159
8     158
7     143
6     136
4     135
5     132
1      84
2      46
Name: count, dtype: int64

df["Customer ID"].value_counts()   #counts how many times each unique value appears